CREATE TABLE [dbo].[Contact]
(
	[Id] INT IDENTITY (1, 1) NOT NULL,
	[Name] NVARCHAR(200) NOT NULL,
	[DDD] INT NOT NULL,
	[Telephone] NVARCHAR(9) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL
	CONSTRAINT [PK_ContactId] PRIMARY KEY NONCLUSTERED ([Id] ASC)
)
