{
 "title": "Main Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Requests Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\"}[5m])) / sum(rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}