apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: 'PostTechFiap.Api'
        scheme: https
        tls_config:
          insecure_skip_verify: true
        static_configs:
          - targets:
              - 'posttechfiap-api-service:443'

      - job_name: 'node-exporter'
        static_configs:
          - targets: 
              - 'node-exporter-service:9100'
